import("//kernel/liteos_m/liteos.gni")

module_name = "interrupt"
kernel_module(module_name) {
  sources = []
  if (defined(LOSCFG_RISCV_LCMP_CLIC)) {
    sources += [ "riscv_lcmp_clic.c" ]
  }
  if (defined(LOSCFG_ARM_GIC_V2)) {
    sources += [ "gic-v2/interrupt.c" ]
  }
  include_dirs = [ "include" ]
}

config("public") {
  include_dirs = [ "include" ]
}
