/*
 * Copyright (c) 2013-2019 Huawei Technologies Co., Ltd. All rights reserved.
 * Copyright (c) 2020-2021 Huawei Device Co., Ltd. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted under the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * X-Macro 单源定义：每行一个枚举名，由 iCunit.h 的枚举和 iCunit.c 的
 * switch 同时展开。加新项只需在此加一行，枚举/字符串自动同步。
 */

ICUNIT_MOD(TEST_TASK)
ICUNIT_MOD(TEST_MEM)
ICUNIT_MOD(TEST_SEM)
ICUNIT_MOD(TEST_MUX)
ICUNIT_MOD(TEST_EVENT)
ICUNIT_MOD(TEST_QUE)
ICUNIT_MOD(TEST_SWTMR)
ICUNIT_MOD(TEST_HWI)
ICUNIT_MOD(TEST_ATO)
ICUNIT_MOD(TEST_CPUP)
ICUNIT_MOD(TEST_SCATTER)
ICUNIT_MOD(TEST_RUNSTOP)
ICUNIT_MOD(TEST_TIMER)
ICUNIT_MOD(TEST_MMU)
ICUNIT_MOD(TEST_TICKLESS)
ICUNIT_MOD(TEST_ROBIN)
ICUNIT_MOD(TEST_LIBC)
ICUNIT_MOD(TEST_WAIT)
ICUNIT_MOD(TEST_VFAT)
ICUNIT_MOD(TEST_YAFFS)
ICUNIT_MOD(TEST_JFFS)
ICUNIT_MOD(TEST_RAMFS)
ICUNIT_MOD(TEST_NFS)
ICUNIT_MOD(TEST_PROC)
ICUNIT_MOD(TEST_FS)
ICUNIT_MOD(TEST_PTHREAD)
ICUNIT_MOD(TEST_COMP)
ICUNIT_MOD(TEST_HWI_HALFBOTTOM)
ICUNIT_MOD(TEST_WORKQ)
ICUNIT_MOD(TEST_WAKELOCK)
ICUNIT_MOD(TEST_TIMES)
ICUNIT_MOD(TEST_LIBM)
ICUNIT_MOD(TEST_SUPPORT)
ICUNIT_MOD(TEST_STL)
ICUNIT_MOD(TEST_MAIL)
ICUNIT_MOD(TEST_MSG)
ICUNIT_MOD(TEST_CP)
ICUNIT_MOD(TEST_SIGNAL)
ICUNIT_MOD(TEST_SCHED)
ICUNIT_MOD(TEST_MTDCHAR)
ICUNIT_MOD(TEST_TIME)
ICUNIT_MOD(TEST_WRITE)
ICUNIT_MOD(TEST_READ)
ICUNIT_MOD(TEST_DYNLOAD)
ICUNIT_MOD(TEST_REGISTER)
ICUNIT_MOD(TEST_SR)
ICUNIT_MOD(TEST_UNAME)
ICUNIT_MOD(TEST_MISC)
ICUNIT_MOD(TEST_EXC)
#if defined(LOSCFG_3RDPARTY_TEST)
ICUNIT_MOD(TEST_THTTPD)
ICUNIT_MOD(TEST_BIDIREFC)
ICUNIT_MOD(TEST_CJSON)
ICUNIT_MOD(TEST_CURL)
ICUNIT_MOD(TEST_FFMPEG)
ICUNIT_MOD(TEST_FREETYPE)
ICUNIT_MOD(TEST_INIPARSER)
ICUNIT_MOD(TEST_JSONCPP)
ICUNIT_MOD(TEST_LIBICONV)
ICUNIT_MOD(TEST_LIBJPEG)
ICUNIT_MOD(TEST_LIBPNG)
ICUNIT_MOD(TEST_OPENEXIF)
ICUNIT_MOD(TEST_OPENSSL)
ICUNIT_MOD(TEST_OPUS)
ICUNIT_MOD(TEST_SQLITE)
ICUNIT_MOD(TEST_TINYXML)
#endif
ICUNIT_MOD(TEST_DRIVERBASE)
ICUNIT_MOD(TEST_DYNLINK)
ICUNIT_MOD(TEST_LMS)
ICUNIT_MOD(TEST_TRACE)
ICUNIT_MOD(TEST_SHELL_MOD)
ICUNIT_MOD(TEST_RWSEM)
